const INITIAL_MEMBERS = [
  { id: 1, name: "谢镇鸿", color: "#FF6B6B", checked: false },
  { id: 2, name: "孟钦辰", color: "#4ECDC4", checked: false },
  { id: 3, name: "刘佳乐", color: "#45B7D1", checked: false },
  { id: 4, name: "郑嘉杰", color: "#FFA07A", checked: false },
  { id: 5, name: "李弘", color: "#98D8C8", checked: false },
  { id: 6, name: "王宏宇", color: "#F7DC6F", checked: false },
  { id: 7, name: "寇泽浩", color: "#BB8FCE", checked: false },
  { id: 8, name: "赵京宽", color: "#85C1E9", checked: false },
  { id: 9, name: "张俊豪", color: "#F8B739", checked: false },
  { id: 10, name: "严守仪", color: "#E74C3C", checked: false },
  { id: 11, name: "张家逸", color: "#2ECC71", checked: false },
  { id: 12, name: "宋晔", color: "#E67E22", checked: false },
  { id: 13, name: "祝旗华", color: "#D81B60", checked: false },
  { id: 14, name: "张宋阳", color: "#5DADE2", checked: false },
  { id: 15, name: "毕笑博", color: "#E84393", checked: false },
  { id: 16, name: "淳冠华", color: "#27AE60", checked: false },
  { id: 17, name: "魏晨", color: "#9B59B6", checked: false },
  { id: 18, name: "胡耀辉", color: "#3498DB", checked: false },
  { id: 19, name: "周子杨", color: "#1ABC9C", checked: false },
  { id: 20, name: "张睿", color: "#E91E63", checked: false },
  { id: 21, name: "钟泳乐", color: "#00BCD4", checked: false },
  { id: 22, name: "贾康玺", color: "#8BC34A", checked: false },
  { id: 23, name: "刘兵彬", color: "#FF9800", checked: false },
  { id: 24, name: "王逸群", color: "#9C27B0", checked: false },
  { id: 25, name: "赵缘杰", color: "#3F51B5", checked: false },
  { id: 26, name: "邓奕琦", color: "#009688", checked: false },
  { id: 27, name: "罗栖宇", color: "#CDDC39", checked: false },
  { id: 28, name: "张博予", color: "#FF5722", checked: false },
  { id: 29, name: "大卫让·苏里坦", color: "#795548", checked: false },
  { id: 30, name: "张权盛", color: "#607D8B", checked: false },
  { id: 31, name: "廖嘉煜", color: "#2196F3", checked: false },
  { id: 32, name: "张祖硕", color: "#FFEB3B", checked: false },
  { id: 33, name: "刘俊成", color: "#4CAF50", checked: false },
  { id: 34, name: "汪博涛", color: "#FFC107", checked: false },
  { id: 35, name: "郭喆", color: "#03A9F4", checked: false },
  { id: 36, name: "金士尧", color: "#8E44AD", checked: false },
  { id: 37, name: "郭峪煊", color: "#16A085", checked: false },
  { id: 38, name: "尹堃镕", color: "#D35400", checked: false },
];

module.exports = { INITIAL_MEMBERS };
